apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: noun-verbs
spec:
  version: "v0.0.1-alpha4"
  homepage: https://github.com/rawkode/kubectl-noun-verb
  shortDescription: "Bringing sanity and composability to kubectl"
  description: "Thanks"
  # 'platforms' specify installation methods for various platforms (os/arch)
  platforms:
    - bin: "kubectl-noun-verb.sh"
      selector:
        matchExpressions:
          - key: "os"
            operator: "In"
            values:
              - darwin
              - linux
      # 'uri' specifies .zip or .tar.gz archive URL of a plugin
      uri: https://github.com/rawkode/kubectl-noun-verb/archive/v0.0.1-alpha3.tar.gz
      # 'sha256' is the sha256sum of the url above
      sha256: 33ec7c758a4497b83352c4176a567616d28a418575bf43ada31bd9bf85abe340
      # 'files' lists which files should be extracted out from downloaded archive
      files:
        - from: "/kubectl-noun-verb*/*.sh"
          to: "."
